language: perl
perl:
    - '5.10'
    - '5.12'
    - '5.14'
    - '5.16'
    - '5.18'
    - '5.20'
env: PERL_CPANM_OPT="--quiet --notest --force --skip-satisfied" RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
before_install:
    - git clone git://github.com/haarg/perl-travis-helper
    - source perl-travis-helper/init
    - build-perl
    - perl -V
    - git config --global user.name 'TravisCI'
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
    - make install
script:
    - make test
after_success:
    - make cover-coveralls
